env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - warn
    - tab
    - SwitchCase: 1
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
  no-debugger:
    - warn
  no-mixed-spaces-and-tabs:
    - warn
  '@typescript-eslint/no-var-requires': 0
